#!/usr/bin/env bash
echo "== Create Bucket"

# check for the bucket name
if [-z "$1" ]; then
    echo "There needs to be a bucket name e.g. ./bucket my-bucket-name"
    exit 1
fi

# if user already provide bucket name than it brings up to this line (10)
BUCKET_NAME=$1 

# command to create a bucket in AWS
aws s3api create-bucket --bucket $BUCKET_NAME --create-bucket-configuration="LocalConstraint=us-east-2" --query Location --output text 

