#!/usr/bin/env bash
echo "== Delete Bucket"

# check for the bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name e.g. ./bucket my-bucket-name"
    exit 1
fi

# if user already provide bucket name than it brings up to this line (10)
BUCKET_NAME=$1 

# command to delete a bucket in AWS
aws s3api delete-bucket --bucket $BUCKET_NAME
