#!/usr/bin/env bash

echo "== put-object"

if [ -z "$1" ]; then
    echo "There needs to be a bucket name e.g. ./bucket my-bucket-name"
    exit 1
fi

# check for filename or prefix

if [ -z "$2" ]; then
    echo "There needs to be a filename prefix e.g. ./sync my-bucket-name my-filename-prefix"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename "$FILENAME")

# AWS command to put the objects into folder
aws s3api put-object --bucket $BUCKET_NAME --body $FILENAME --key $OBJECT_KEY