#!/usr/bin/env bash
# https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/

echo "== deploy s3 bucket via CFN"
STACK_NAME="cfn-s3-simple-kp"

aws cloudformation deploy --template-file template.yaml --no-execute-chageset --region us-east-1 --stack-name $STACK_NAME
