
AWSTemplateFormatVersion: 2010-09-09
Description: A sample CloudFormation template with YAML comments.
Resources:
  S3Bucket:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    Type: 'AWS::S3::Bucket'
    
    